# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-30 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetNum', models.CharField(default='', max_length=128, verbose_name='资产编号')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称')),
                ('model', models.CharField(default='', max_length=30, verbose_name='型号')),
                ('status', models.CharField(choices=[('0', '闲置'), ('1', '在用'), ('2', '维修'), ('3', '报废'), ('4', '售出')], default='1', max_length=20, verbose_name='资产状态')),
                ('assetCount', models.IntegerField(default=1, verbose_name='资产数量')),
                ('assetUnit', models.CharField(default='个', max_length=20, verbose_name='资产单位')),
                ('operator', models.CharField(default='', max_length=20, verbose_name='入库人')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
            },
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_user', models.CharField(max_length=20, verbose_name='上传人')),
                ('file_content', models.ImageField(blank=True, null=True, upload_to='asset_file/%Y/%m', verbose_name='资产文件')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.Asset', verbose_name='资产')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=20, verbose_name='操作人')),
                ('desc', models.TextField(default='', verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Asset', verbose_name='资产')),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='仓库名称', max_length=30, verbose_name='仓库名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产仓库',
            },
        ),
        migrations.CreateModel(
            name='AssetUseAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='详细地址', max_length=30, verbose_name='详细地址')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产使用地址',
            },
        ),
        migrations.CreateModel(
            name='AssetUseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useCount', models.IntegerField(default=1, verbose_name='领取数量')),
                ('operator', models.CharField(max_length=20, verbose_name='领取人')),
                ('area', models.TextField(default='', verbose_name='使用地区')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('party', models.CharField(choices=[('0', '自用'), ('1', '外包方使用')], default='0', max_length=1, verbose_name='领取方')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.Asset', verbose_name='资产')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, verbose_name='客户单位')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('name', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=30, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '客户管理',
                'verbose_name_plural': '客户管理',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, verbose_name='设备编号')),
                ('equipment_model', models.CharField(default='', max_length=50, verbose_name='设备型号')),
                ('buy_date', models.DateField(verbose_name='购买日期')),
                ('warranty_date', models.DateField(verbose_name='质保日期')),
                ('accounting', models.BooleanField(default=False, verbose_name='费用核算状态')),
                ('config_desc', models.TextField(blank=True, null=True, verbose_name='配置说明')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.Customer', verbose_name='客户信息')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备管理',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类型名称', max_length=30, verbose_name='类型名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='记录内容')),
                ('is_reminding', models.BooleanField(default=False, verbose_name='邮件消息提醒')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, verbose_name='公司名称')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('linkname', models.CharField(max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人')),
            ],
            options={
                'verbose_name': '分销商管理',
                'verbose_name_plural': '分销商管理',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.EquipmentType', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_info',
            field=models.ManyToManyField(blank=True, to='adm.ServiceInfo', verbose_name='服务记录'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.Supplier', verbose_name='分销商'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assetType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adm.AssetType', verbose_name='资产仓库'),
        ),
    ]
