# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-30 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dueDate',
            field=models.DateField(blank=True, null=True, verbose_name='到期日期'),
        ),
        migrations.AddField(
            model_name='asset',
            name='dueremind',
            field=models.CharField(choices=[('0', '不提醒'), ('1', '提醒')], default='0', max_length=20, verbose_name='到期提醒'),
        ),
    ]
