# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-31 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20190731_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuselog',
            name='back_count',
            field=models.IntegerField(default=1, verbose_name='归还数量'),
        ),
        migrations.AddField(
            model_name='assetuselog',
            name='back_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 7, 31), null=True, verbose_name='归回日期'),
        ),
        migrations.AddField(
            model_name='assetuselog',
            name='give_back',
            field=models.CharField(choices=[('0', '自用'), ('1', '外包方使用')], default='0', max_length=1, verbose_name='是否归回'),
        ),
    ]
