# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-31 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0004_auto_20190731_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuselog',
            name='back_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='归还记录员'),
        ),
    ]
