# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-06 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_assetuselog_back_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuselog',
            name='title',
            field=models.TextField(default='', verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='dueDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='到期日期'),
        ),
        migrations.AlterField(
            model_name='assetuselog',
            name='back_count',
            field=models.IntegerField(default=0, verbose_name='归还数量'),
        ),
        migrations.AlterField(
            model_name='assetuselog',
            name='back_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='归还日期'),
        ),
    ]
