# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-29 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_auto_20190906_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetuselog',
            name='use_time',
            field=models.DateField(blank=True, null=True, verbose_name='预计归还时间'),
        ),
    ]
