# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_assetuselog_use_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetuselog',
            name='use_time',
            field=models.DateField(blank=True, null=True, verbose_name='预计归还日期'),
        ),
    ]
