# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0008_auto_20191104_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('super_adm', models.BooleanField(default=False, verbose_name='是否有全部部门管理权限')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='资产管理员')),
            ],
        ),
        migrations.CreateModel(
            name='AssetWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.AssetDepartment', verbose_name='所属资产部门')),
            ],
        ),
    ]
