# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-05 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20191205_0902'),
        ('adm', '0008_auto_20191104_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(max_length=50, verbose_name='资产名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('status', models.CharField(choices=[('0', '闲置'), ('1', '在用'), ('2', '维修'), ('3', '报废'), ('4', '售出')], default='0', max_length=5, verbose_name='资产状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('due_time', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('type', models.CharField(max_length=20, verbose_name='型号')),
                ('remark', models.TextField(max_length=500, verbose_name='备注信息')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Structure', verbose_name='所属部门')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_operator', to=settings.AUTH_USER_MODEL, verbose_name='录入人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_user', to=settings.AUTH_USER_MODEL, verbose_name='使用人')),
            ],
        ),
        migrations.CreateModel(
            name='AssetWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('is_all_view', models.BooleanField(default=False, verbose_name='是否所有人可见')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Structure', verbose_name='所属资产部门')),
            ],
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.AssetWarehouse', verbose_name='所属仓库'),
        ),
    ]
