# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_assetinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetinfo',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='资产名称'),
            preserve_default=False,
        ),
    ]
