# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-06 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0010_auto_20191206_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEditFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('content', models.CharField(max_length=20, verbose_name='内容')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.AssetInfo', verbose_name='相关资产')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
        ),
    ]
