# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-29 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0012_assetinfo_is_all_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetinfo',
            name='is_all_view',
        ),
        migrations.AddField(
            model_name='assetwarehouse',
            name='is_all_view',
            field=models.BooleanField(default=False, verbose_name='是否所有人可见'),
        ),
    ]
