# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-13 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0012_auto_20191206_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('purpose', models.CharField(blank=True, max_length=30, null=True, verbose_name='用途')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='预计归还时间')),
                ('status', models.CharField(max_length=10, verbose_name='状态')),
                ('use_status', models.CharField(max_length=10, verbose_name='使用状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.AssetInfo', verbose_name='物资')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_proposer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
        ),
        migrations.CreateModel(
            name='AssetApproveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pass', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否通过')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='审批意见')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('asset_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adm.AssetApprove', verbose_name='物资申请')),
            ],
        ),
    ]
