# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-17 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0013_assetapprove_assetapprovedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetapprove',
            name='return_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_operator', to=settings.AUTH_USER_MODEL, verbose_name='归还操作人'),
        ),
        migrations.AddField(
            model_name='assetapprove',
            name='return_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='归还数量'),
        ),
        migrations.AddField(
            model_name='assetapprove',
            name='t_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='归还日期'),
        ),
    ]
