# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-18 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0015_auto_20191217_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetapprove',
            name='return_quantity',
            field=models.IntegerField(default=0, verbose_name='归还数量'),
        ),
    ]
