# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0016_auto_20191218_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetapprove',
            name='type',
            field=models.CharField(default=0, max_length=10, verbose_name='类型'),
            preserve_default=False,
        ),
    ]
