# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191206_0916'),
        ('adm', '0017_assetapprove_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetapprove',
            name='transfer_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Structure', verbose_name='转移部门'),
        ),
        migrations.AddField(
            model_name='assetapprove',
            name='transfer_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adm.AssetWarehouse', verbose_name='转移仓库'),
        ),
    ]
