# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-27 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0013_auto_20191129_1140'),
        ('adm', '0018_auto_20191219_1440'),
    ]

    operations = [
    ]
