# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190829_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='adm_list',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部门管理员'),
        ),
    ]
