# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-05 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_structure_adm_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='部门资产管理员'),
        ),
        migrations.AddField(
            model_name='structure',
            name='super_adm',
            field=models.BooleanField(default=False, verbose_name='是否有全部部门管理权限'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='adm_list',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部门工单管理员'),
        ),
    ]
