# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-30 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191206_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dep_administrator',
            field=models.BooleanField(default=False, verbose_name='是否是部门物资管理员'),
        ),
    ]
