# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OilWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=10, verbose_name='操作人')),
                ('refuel_time', models.DateField(verbose_name='加油时间')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('mileage', models.FloatField(verbose_name='加油前公里数')),
                ('weight', models.FloatField(verbose_name='加油量(升)')),
                ('price', models.FloatField(verbose_name='油量单价(升)')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, verbose_name='车牌号')),
                ('department', models.CharField(max_length=20, verbose_name='所属部门')),
                ('type', models.CharField(max_length=30, verbose_name='车型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='oilwear',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oilWear.Vehicle', verbose_name='载具'),
        ),
    ]
