# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-14 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oilWear', '0003_vehicle_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='oilwear',
            name='operator',
            field=models.CharField(max_length=10, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
