# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-15 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oilWear', '0006_auto_20191115_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilwear',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='提交人'),
        ),
    ]
