# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-09 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('0', '对外付款职位人')], max_length=10, verbose_name='角色名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_role', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
            ],
        ),
    ]
