# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-27 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='审批单号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(choices=[('0', '立项审批'), ('1', '出差审批')], default='0', max_length=10, verbose_name='审批类型')),
                ('status', models.CharField(choices=[('0', '等待审批'), ('1', '审批中'), ('2', '审批完成'), ('3', '审批被退回')], default='0', max_length=10, verbose_name='审批状态')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('thing', models.CharField(blank=True, max_length=300, verbose_name='事件')),
                ('cost', models.CharField(blank=True, max_length=12, verbose_name='费用')),
                ('invoice_type', models.CharField(blank=True, choices=[('0', '增值税普通发票'), ('1', '增值税专用发票')], default='0', max_length=10, verbose_name='发票类型')),
                ('payee', models.CharField(blank=True, max_length=300, verbose_name='收款方')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='银行账户')),
                ('bank_info', models.CharField(blank=True, max_length=300, verbose_name='开户行')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cretor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposer', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('next_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_order', to=settings.AUTH_USER_MODEL, verbose_name='当前审批人')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder', to='users.Structure', verbose_name='申请部门')),
            ],
            options={
                'verbose_name': '申报信息',
                'verbose_name_plural': '申报信息',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=300, verbose_name='审批流程')),
                ('factor_type', models.CharField(choices=[('0', '时间'), ('1', '金额')], max_length=10, verbose_name='审批条件类型')),
                ('factor', models.CharField(max_length=50, verbose_name='审批条件')),
                ('carbon', models.CharField(max_length=300, verbose_name='抄送人')),
                ('order_type', models.CharField(choices=[('0', '立项审批'), ('1', '出差审批')], max_length=10, verbose_name='审批类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorderflow', to='users.Structure', verbose_name='申请部门')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorderflowupdater', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '审批流程表',
                'verbose_name_plural': '审批流程表',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('0', '同意'), ('1', '不同意')], max_length=10, verbose_name='审批意见')),
                ('desc', models.CharField(default='', max_length=500, verbose_name='审批意见详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorderlog', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='申报表id')),
            ],
            options={
                'verbose_name': '审批日志',
                'verbose_name_plural': '审批日志',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('0', '退回'), ('1', '派发'), ('2', '执行'), ('3', '确认')], max_length=10, verbose_name='记录类型')),
                ('content', models.CharField(default='', max_length=500, verbose_name='记录内容')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='实施文档')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.WorkOrder', verbose_name='工单信息')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
            },
        ),
    ]
