# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='advance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='是否预支'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='becity',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='出发地点'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='destination',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='目标地点'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='people',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='随行人员'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='transport',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='交通工具'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='bank_account',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='银行账户'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='bank_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='开户行'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('0', '增值税普通发票'), ('1', '增值税专用发票')], default='0', max_length=10, null=True, verbose_name='发票类型'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='payee',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='收款方'),
        ),
    ]
