# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('personal', '0002_auto_20190628_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderlog',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorderlog', to='users.Structure', verbose_name='审批时所在部门'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='number',
            field=models.CharField(max_length=20, verbose_name='审批单号'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder', to='users.Structure', verbose_name='申请时所在部门'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(max_length=50, verbose_name='工作内容'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='transport',
            field=models.CharField(blank=True, choices=[('0', '立项审批'), ('1', '出差审批')], max_length=300, null=True, verbose_name='交通工具'),
        ),
    ]
