# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-15 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_businessapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='title',
            field=models.CharField(default='出差事项', max_length=50, verbose_name='工作内容'),
            preserve_default=False,
        ),
    ]
