# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-15 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_businessapply_all_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='days',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='出差天数'),
        ),
        migrations.AddField(
            model_name='businessapply',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessapply',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
            preserve_default=False,
        ),
    ]
