# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20190715_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='type',
            field=models.CharField(choices=[('0', '立项审批'), ('1', '出差审批')], default='0', max_length=10, verbose_name='审批类型'),
        ),
    ]
