# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_businessapply_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('0', '增值税普通发票'), ('1', '增值税专用发票'), ('3', '增值税专用发票')], default='0', max_length=10, null=True, verbose_name='发票类型'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('0', '增值税普通发票'), ('1', '增值税专用发票'), ('3', '增值税专用发票')], default='0', max_length=10, null=True, verbose_name='发票类型'),
        ),
    ]
