# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20190717_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderflow',
            name='pro_type',
            field=models.CharField(choices=[('0', '立项'), ('1', '报销')], default='0', max_length=10, verbose_name='报销立项分类'),
        ),
    ]
