# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-09 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_workorderflow_pro_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='advance',
            field=models.CharField(choices=[('0', '不预支'), ('1', '预支')], default='0', max_length=10, verbose_name='是否预支'),
        ),
    ]
