# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20190809_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='adv_payment',
            field=models.CharField(choices=[('0', '没完成预支'), ('1', '完成预支')], default='0', max_length=10, verbose_name='完成预付款'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='开始时间'),
        ),
    ]
