# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-26 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20190812_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapply',
            name='status',
            field=models.CharField(choices=[('-1', '可以申请'), ('0', '等待审批'), ('1', '审批中'), ('2', '审批完成'), ('3', '审批被退回'), ('4', '付款完成'), ('5', '等待付款')], default='-1', max_length=10, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='title',
            field=models.TextField(verbose_name='工作内容'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('0', '等待审批'), ('1', '审批中'), ('2', '审批完成'), ('3', '审批被退回'), ('4', '预付款完成'), ('5', '等待预付款'), ('6', '报销完成')], default='0', max_length=10, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.TextField(verbose_name='工作内容'),
        ),
    ]
