# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-11 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20190826_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='other_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='其他费用'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='acco_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='住宿费用'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='all_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='总费用'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='food_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='餐饮费用'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='rece_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='招待费用'),
        ),
        migrations.AlterField(
            model_name='businessapply',
            name='tran_fee',
            field=models.CharField(blank=True, default=0, max_length=12, verbose_name='交通费用'),
        ),
    ]
