# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-09-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20190911_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessapply',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y/%m', verbose_name='附件'),
        ),
    ]
