# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-05 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0021_businessapply_t_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapply',
            name='status',
            field=models.CharField(choices=[('-1', '可以申请'), ('0', '等待审批'), ('1', '审批中'), ('2', '审批完成'), ('3', '审批被退回'), ('4', '报销完成'), ('5', '等待付款')], default='-1', max_length=10, verbose_name='审批状态'),
        ),
    ]
