# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_auto_20191205_0902'),
    ]

    operations = [

    ]
