# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-05 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_auto_20191205_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordercard',
            name='time',
            field=models.IntegerField(max_length=10, null=True, verbose_name='使用次数'),
        ),
    ]
