# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0022_auto_20191205_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapply',
            name='t_title',
            field=models.CharField(max_length=100, verbose_name='申请标题'),
        ),
    ]
