# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-06 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0023_workordercard_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='advise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back', models.TextField(max_length=1000, verbose_name='意见反馈')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建议人')),
            ],
        ),
    ]
