# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-13 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_advise'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=10, verbose_name='花销类型')),
            ],
        ),
        migrations.AddField(
            model_name='advise',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advise',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='是否已解决'),
        ),
    ]
