# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_auto_20191213_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_id', models.IntegerField(blank=True)),
                ('fee_type', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='feeid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.FeeType', verbose_name='费用id'),
        ),
    ]
