# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-18 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0027_auto_20191218_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderType',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='t_title',
        ),
    ]
