# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-26 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0028_auto_20191218_1513'),
        ('personal', '0023_auto_20191217_0927'),
    ]

    operations = [
    ]
