# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-30 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0029_merge_20191226_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkOrderType',
        ),
        migrations.RemoveField(
            model_name='businessapply',
            name='t_title',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='t_title',
        ),
    ]
