# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-23 16:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('status', models.CharField(choices=[('0', '停用'), ('1', '启用')], default='1', max_length=10, verbose_name='状态')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='file/%y/%m', verbose_name='附件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('status', models.CharField(choices=[('0', '停用'), ('1', '启用')], default='1', max_length=10, verbose_name='状态')),
            ],
        ),
        migrations.AddField(
            model_name='bulletin',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin', to='bulletin.BulletinType', verbose_name='类型'),
        ),
    ]
