# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
